export const AUTH_LOGGED_IN = 'Authenticated'
export const AUTH_LOGGED_IN_BADGE = 'Logged In'
export const AUTH_LOGGED_IN_DESCRIPTION = 'You are signed in and can access protected features'
export const AUTH_SIGN_OUT = 'Sign Out'
export const AUTH_SIGNING_OUT = 'Signing out...'
