export const AUTH_LOADING = 'Loading session...'
export const AUTH_LOGGED_IN = 'Authenticated'
export const AUTH_LOGGED_IN_BADGE = 'Logged In'
export const AUTH_LOGGED_IN_DESCRIPTION = 'You are signed in and can access protected features'
export const AUTH_SIGN_OUT = 'Sign Out'
export const AUTH_SIGNING_OUT = 'Signing out...'
export const AUTH_GUEST = 'Authentication'
export const AUTH_GUEST_BADGE = 'Guest'
export const AUTH_GUEST_DESCRIPTION =
  'Sign in with a magic link to access protected features like sending chat messages'
export const AUTH_EMAIL_LABEL = 'Email'
export const AUTH_EMAIL_PLACEHOLDER = 'you@example.com'
export const AUTH_SEND_LINK = 'Send Magic Link'
export const AUTH_SENDING = 'Sending...'
export const AUTH_MAGIC_LINK_ERROR = 'Failed to send magic link'
export const AUTH_MAGIC_LINK_SUCCESS = 'Magic link sent! Check your console (dev mode).'
export const AUTH_DEV_HINT = 'In development, the magic link URL is logged to the server console.'
